server:
    port: 8761
    #servlet:
        #path: /custom
eureka:
    instance:
        hostname: localhost
        #statusPageUrlPath: ${server.servlet.path}/info
        #healthCheckUrlPath: ${server.servlet.path}/health
    client:
        registerWithEureka: false
        fetchRegistry: false
        serviceUrl:
            defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
            healthcheck:
                enabled: true
    server:
        enable-self-preservation: false #关闭保护机制，本地可关闭，正式服务需开启