spring:
  application:
    name: eureka-client-consumer
server:
  port: 9002
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
eureka-client-consumer:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.IRule
